# Generated by Django 4.2.13 on 2024-06-22 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streaming', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('payment_type', models.PositiveSmallIntegerField(choices=[(1, 'Instant Payment'), (2, 'Manual Payment')])),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Need confirmation'), (3, 'Success'), (4, 'Failed')], default=1)),
                ('success_at', models.DateTimeField(null=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('va_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_file', models.FileField(blank=True, null=True, upload_to='')),
                ('streaming', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='streaming.streaming')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
