# Generated by Django 4.2.13 on 2024-06-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='bank_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
